import {
  AlertTriangle,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ClipboardCheck,
  ClipboardList,
  Compass,
  FileText,
  GraduationCap,
  HeartHandshake,
  Inbox,
  Layers,
  LayoutDashboard,
  Library,
  ListChecks,
  MailPlus,
  Megaphone,
  MessageSquare,
  ScanSearch,
  Scale,
  ScrollText,
  Settings,
  SlidersHorizontal,
  Tags,
  TrendingUp,
  Upload,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  type LucideIcon,
} from "lucide-react";

export const sidebarIconMap: Record<string, LucideIcon> = {
  LayoutDashboard,
  TrendingUp,
  CalendarCheck,
  GraduationCap,
  Settings,
  CalendarDays,
  Layers,
  ClipboardList,
  ClipboardCheck,
  AlertTriangle,
  Users,
  UserCog,
  BarChart3,
  BookOpen,
  CalendarClock,
  ListChecks,
  Bell,
  Megaphone,
  Building2,
  CalendarRange,
  HeartHandshake,
  MailPlus,
  Upload,
  UserCheck,
  Award,
  Compass,
  FileText,
  Inbox,
  Library,
  MessageSquare,
  ScanSearch,
  Scale,
  ScrollText,
  SlidersHorizontal,
  Tags,
  UsersRound,
};

export function getSidebarIcon(name: string): LucideIcon {
  return sidebarIconMap[name] ?? LayoutDashboard;
}
