import {
  AlertTriangle,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ClipboardCheck,
  ClipboardList,
  GraduationCap,
  HeartHandshake,
  Layers,
  LayoutDashboard,
  ListChecks,
  MailPlus,
  Megaphone,
  Settings,
  TrendingUp,
  Upload,
  UserCheck,
  UserCog,
  Users,
  type LucideIcon,
} from "lucide-react";

export const sidebarIconMap: Record<string, LucideIcon> = {
  LayoutDashboard,
  TrendingUp,
  CalendarCheck,
  GraduationCap,
  Settings,
  CalendarDays,
  Layers,
  ClipboardList,
  ClipboardCheck,
  AlertTriangle,
  Users,
  UserCog,
  BarChart3,
  BookOpen,
  CalendarClock,
  ListChecks,
  Bell,
  Megaphone,
  Building2,
  CalendarRange,
  HeartHandshake,
  MailPlus,
  Upload,
  UserCheck,
};

export function getSidebarIcon(name: string): LucideIcon {
  return sidebarIconMap[name] ?? LayoutDashboard;
}
