spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edumetric
    username: postgres
    password: root123
  jpa:
    properties:
      hibernate:
        format_sql: true
  liquibase:
    contexts: default,dev,demo

logging:
  level:
    com.edumetric.backend: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
